#version: '3.9-slim'

services:
  nextjs:
    build: ./react_app
    ports:
      - "3000:3000"
    volumes:
      - ./react_app:/usr/src/app  # Application code volume
      - ./data:/app/data  # Shared data volume
    depends_on:
      - flask

  flask:
    build: ./flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app:/usr/src/app  # Application code volume
      - ./data:/app/data  # Shared data volume